services:
  mongodb:
    image: mongo:latest
    container_name: ${MONGODB_USER}
    restart: unless-stopped

    ports:
      - ${MONGODB_PORT}:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
      MONGO_INITDB_DATABASE: ${MONGODB_DBNAME}

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
