basePath: /v1
host: localhost:4000
info:
  contact:
    email: no-email@no-email
    name: Saleh Ghazimoradi
  description: A modern e-commerce API built with Go, MongoDB, and gRPC
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: X-Gopher API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    description: JWT Bearer token (e.g., "Bearer {token}")
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
